#!/bin/sh
set -e

# PostgreSQL SSL initialization script

echo "Configuring PostgreSQL SSL..."

# Check if SSL certificates exist
if [ -f /var/lib/postgresql/ssl/server.crt ] && [ -f /var/lib/postgresql/ssl/server.key ]; then
    echo "SSL certificates found. Configuring SSL mode..."

    # Set proper permissions on SSL files
    chown postgres:postgres /var/lib/postgresql/ssl/server.crt
    chown postgres:postgres /var/lib/postgresql/ssl/server.key
    chmod 600 /var/lib/postgresql/ssl/server.key
    chmod 644 /var/lib/postgresql/ssl/server.crt

    # Set permissions on CA cert if exists
    if [ -f /var/lib/postgresql/ssl/ca.crt ]; then
        chown postgres:postgres /var/lib/postgresql/ssl/ca.crt
        chmod 644 /var/lib/postgresql/ssl/ca.crt
    fi

    # Update postgresql.conf to enable SSL
    cat >> "${PGDATA}/postgresql.conf" <<'EOF'

# SSL Configuration (added by init-ssl.sh)
ssl = on
ssl_cert_file = '/var/lib/postgresql/ssl/server.crt'
ssl_key_file = '/var/lib/postgresql/ssl/server.key'
ssl_prefer_server_ciphers = on
ssl_ciphers = 'HIGH:MEDIUM:+3DES:!aNULL'
ssl_min_protocol_version = 'TLSv1.2'
EOF

    # Backup original pg_hba.conf
    cp "${PGDATA}/pg_hba.conf" "${PGDATA}/pg_hba.conf.backup"

    # Replace pg_hba.conf to require SSL for all TCP/IP connections
    cat > "${PGDATA}/pg_hba.conf" <<'EOF'
# PostgreSQL Client Authentication Configuration File
# Generated by init-ssl.sh

# TYPE  DATABASE        USER            ADDRESS                 METHOD

# Local connections (Unix domain socket)
local   all             all                                     trust

# IPv4 local connections (require SSL)
hostssl all             all             127.0.0.1/32            scram-sha-256

# IPv4 connections from Docker network (require SSL)
hostssl all             all             0.0.0.0/0               scram-sha-256

# IPv6 local connections (require SSL)
hostssl all             all             ::1/128                 scram-sha-256

# Reject non-SSL connections
hostnossl all           all             all                     reject
EOF

    echo "PostgreSQL SSL configuration completed."
    echo "Original pg_hba.conf backed up to pg_hba.conf.backup"
else
    echo "WARNING: SSL certificates not found at /var/lib/postgresql/ssl/"
    echo "PostgreSQL will start without SSL. This is NOT recommended for production."
fi
